Bieb.Web/Models/Stories/EditStoryModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Bieb.Domain.Entities;

namespace Bieb.Web.Models.Stories
{
    public class EditStoryModel : EditPublishableModel<Story>
    {
        public EditStoryModel()
        { }

        public EditStoryModel(string bookTitle)
        {
            this.BookTitle = bookTitle;
        }

        public string BookTitle { get; internal set; }
    }
}

Bieb.Web/Models/Stories/EditStoryModelMapper.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Bieb.Domain.Entities;
using Bieb.Domain.Repositories;
using Bieb.Web.Localization;
using Bieb.Web.Models.Books;

namespace Bieb.Web.Models.Stories
{
    public class EditStoryModelMapper : EditPublishableModelMapper<Story, EditStoryModel>
    {
        public EditStoryModelMapper(IEntityRepository<Publisher> publishers, IEntityRepository<Person> people, IBookRepository books, IIso639LanguageDisplayer iso639LanguageDisplayer)
            : base(publishers, people, books, iso639LanguageDisplayer)
        {}

        public override void MergeEntityWithModel(Story entity, EditStoryModel model)
        {
            base.MergeEntityWithModel(entity, model);
        }

        public override EditStoryModel ModelFromEntity(Story entity)
        {
            var model = base.ModelFromEntity(entity);

            model.BookTitle = entity.Book.Title;

            return model;
        }
    }
}

Bieb.Web/Models/Stories/LinkableStoryModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Bieb.Domain.Entities;

namespace Bieb.Web.Models.Stories
{
    public class LinkableStoryModel : LinkableEntityModel<Story>
    {
        public LinkableStoryModel(Story story)
        {
            Id = story.Id;
            Text = story.Title;
        }
    }

    public static class LinkableStoryModelExtensions
    {
        public static LinkableStoryModel AsLinkableStoryModel(this Story story)
        {
            return story == null
                       ? null
                       : new LinkableStoryModel(story);
        }
    }
}

Bieb.Web/Models/Stories/ViewStoryModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Bieb.Domain.Entities;
using Bieb.Web.Models.Books;
using Bieb.Web.Models.People;
using Bieb.Web.Models.Publishers;

namespace Bieb.Web.Models.Stories
{
    public class ViewStoryModel : ViewEntityModel<Story>
    {
        public ViewStoryModel(Story story) : base(story)
        {
            Title = story.Title;
            Subtitle = story.Subtitle;
            Year = story.Year;
            HasLanguage = !string.IsNullOrEmpty(story.Iso639LanguageId);
            HasTags = story.Tags.Any();
            Tags = string.Join(", ", story.Tags);
            Book = story.Book.AsLinkableBookModel();
            Authors = story.Authors.Select(a => a.AsLinkablePersonModel());
            Translators = story.Translators.Select(a => a.AsLinkablePersonModel());
            Publisher = story.Publisher.AsLinkablePublisherModel();
            ReferenceStory = story.ReferenceStory.AsViewStoryModel();
            SiblingStories = story.Book == null ? new List<LinkableStoryModel>() : story.Book.Stories.Where(s => s.Value != story).Select(s => s.Value.AsLinkableStoryModel());
        }

        public string Title { get; set; }
        public string Subtitle { get; set; }
        public int? Year { get; set; }
        public bool HasLanguage { get; set; }
        public string Language { get; set; }

        public bool HasTags { get; set; }
        public string Tags { get; set; }

        public LinkableBookModel Book { get; set; }
        public LinkablePublisherModel Publisher { get; set; }
        public IEnumerable<LinkablePersonModel> Authors { get; set; }
        public IEnumerable<LinkablePersonModel> Translators { get; set; }
        public IEnumerable<LinkableStoryModel> SiblingStories { get; set; } 

        public ViewStoryModel ReferenceStory { get; set; }
    }

    public static class ViewStoryModelExtensions
    {
        public static ViewStoryModel AsViewStoryModel(this Story story)
        {
            return story == null
                       ? null
                       : new ViewStoryModel(story);
        }
    }
}

Bieb.Web/Models/Stories/ViewStoryModelMapper.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Bieb.Domain.Entities;
using Bieb.Web.Localization;

namespace Bieb.Web.Models.Stories
{
    public class ViewStoryModelMapper : IViewEntityModelMapper<Story, ViewStoryModel>
    {
        private readonly IIso639LanguageDisplayer iso639LanguageDisplayer;

        public ViewStoryModelMapper(IIso639LanguageDisplayer iso639LanguageDisplayer)
        {
            this.iso639LanguageDisplayer = iso639LanguageDisplayer;
        }

        public ViewStoryModel ModelFromEntity(Story entity)
        {
            return new ViewStoryModel(entity)
                       {
                           Language = iso639LanguageDisplayer.GetLocalizedIso639LanguageResource(entity.Iso639LanguageId)
                       };
        }
    }
}

Bieb.Web/Controllers/StoriesController.cs
using System;
using System.Diagnostics.CodeAnalysis;
using System.Web.Mvc;
using Bieb.Domain.Entities;
using Bieb.Domain.Repositories;
using Bieb.Web.Models;
using Bieb.Web.Models.Stories;

namespace Bieb.Web.Controllers
{
    public class StoriesController : EntityController<Story, ViewStoryModel, EditStoryModel>
    {
        public StoriesController(IEntityRepository<Story> repository,
                                 IViewEntityModelMapper<Story, ViewStoryModel> viewStoryModelMapper,
                                 IEditEntityModelMapper<Story, EditStoryModel> editEntityModelMapper)
            : base(repository, viewStoryModelMapper, editEntityModelMapper)
        { }

        public override ActionResult Index(int pageSize = 25, int page = 1)
        {
            return RedirectToAction("Index", "Books");
        }

        [ExcludeFromCodeCoverage] // TODO: this property is overridden because we *have* to, but it's of no use currently.
        protected override System.Linq.Expressions.Expression<Func<Story, IComparable>> SortFunc
        {
            get { return s => s.TitleSort; }
        }
    }
}

Bieb.Web/Controllers/StoryController.cs
using System;
using System.Web.Mvc;
using Bieb.Domain.Entities;
using Bieb.Domain.Repositories;

namespace Bieb.Web.Controllers
{
    public class StoryController : EntityController<Story>
    {
        public StoryController(IEntityRepository<Story> repository)
            : base(repository)
        { }

        public override ActionResult Index(int pageSize = 25, int page = 1)
        {
            throw new NotImplementedException("Listing an index of stories is not allowed. You can get there via Books and Persons");
        }

        protected override System.Linq.Expressions.Expression<Func<Story, IComparable>> SortFunc
        {
            get { return s => s.TitleSort; }
        }
    }
}

Bieb.Web/Views/Stories/Card.cshtml
@model Bieb.Web.Models.Stories.ViewStoryModel

<div class="panel panel-primary">
    <div class="panel-body">
        <h1>@Html.DisplayFor(model => model.Title)</h1>
        @if (Model.Subtitle != null)
        { 
            <h2>@Html.DisplayFor(model => model.Subtitle)</h2>
        }
        <ul>
            @if (Model.Book != null)
            {
                <li>@BiebResources.StoryStrings.From @Html.ActionLink(Model.Book.Text, "Details", new { id = Model.Book.Id, controller = "Books" })</li>
            }
            @if (Model.HasTags)
            { 
                <li>@BiebResources.SharedStrings.Tags: @Model.Tags</li>
            }
            @if (Model.Publisher != null)
            {
                <li>@BiebResources.SharedStrings.Publisher: @Html.ActionLink(Model.Publisher.Text, "Details", new { id = Model.Publisher.Id, controller = "Publishers" })</li>
            }
        </ul>

        @if (Model.ReferenceStory != null)
        {
            <h2>@BiebResources.SharedStrings.Original:</h2>
            <ul>
                @if (Model.Title != Model.ReferenceStory.Title)
                {
                    // No ActionLink yet, a page for a ReferenceStory is a bit too boring for that
                    <li>@BiebResources.SharedStrings.Title: @Model.ReferenceStory.Title</li>
                }
                @if (Model.ReferenceStory.Publisher != null)
                {
                    <li>
                        @BiebResources.SharedStrings.Publisher: 
                @Html.ActionLink(Model.ReferenceStory.Publisher.Text, "Details", new { id = Model.ReferenceStory.Publisher.Id, controller = "Publishers" })
                    </li>
                }
                @if (Model.ReferenceStory.Year.HasValue)
                {
                    <li>
                        @BiebResources.SharedStrings.Published:
                        <span>@Model.ReferenceStory.Year.Value</span>
                    </li>
                }
                @if (Model.ReferenceStory.HasLanguage)
                {
                    <li>
                        @BiebResources.SharedStrings.Language:
                        <span>@Model.ReferenceStory.Language</span>
                    </li>
                }
            </ul>
        }
    </div>
</div>

Bieb.Web/Views/Stories/Details.cshtml
@model Bieb.Web.Models.Stories.ViewStoryModel

@{
    ViewBag.Title = "Details";
}

@if (User.Identity.IsAuthenticated)
{
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            @using (Html.BeginForm("Delete", "Stories", FormMethod.Post, new { @class = "navbar-form navbar-left" }))
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(model => model.Id)
                
                <a href="@Url.Action("Edit", "Stories", new { Model.Id })" class="btn btn-default">
                    <i class="glyphicon glyphicon-pencil"></i>
                    <span class="hidden-xs">@BiebResources.SharedStrings.Edit</span>
                </a>
                
                <button class="btn btn-default" type="submit" onclick="return confirm('@BiebResources.SharedStrings.SimpleConfirmQuestion')">
                    <i class="glyphicon glyphicon-trash"></i>
                    <span class="hidden-xs">@BiebResources.SharedStrings.Delete</span>
                </button>
            }
        </div>
    </nav>
}

<div class="row">

    <div class="col-md-4">
        @{ Html.RenderPartial("Card", Model); }
    </div>

    <div class="col-md-8">
        @if (Model.Authors.Any())
        {
            <h4>@BiebResources.SharedStrings.Authors</h4>
            <ul>
            @foreach (var person in Model.Authors)
            {
                <li>@Html.ActionLink(person.Text, "Details", new { controller = "people", id = person.Id })</li>
            }
            </ul>
        }

        @if (Model.Translators.Any())
        {
            <h4>@BiebResources.SharedStrings.Translators</h4>
            <ul>
            @foreach (var person in Model.Translators)
            {
                <li>@Html.ActionLink(person.Text, "Details", new { controller = "people", id = person.Id })</li>
            }
            </ul>
        }
        
        @if (Model.SiblingStories.Any())
        {
            <h4>@BiebResources.StoryStrings.Siblings</h4>
            <ul>
            @foreach (var story in Model.SiblingStories)
            {
                <li>@Html.ActionLink(story.Text, "Details", new { controller = "Stories", id = story.Id })</li>
            }
            </ul>
        }
    </div>

</div>

Bieb.Web/Views/Stories/Edit.cshtml
@model Bieb.Web.Models.Stories.EditStoryModel

@{
    ViewBag.Title = "Edit";
}

<h1>@Model.Title</h1>

@using (Html.BeginForm("Save", "Stories"))
{
    <div class="form-horizontal">
        @Html.AntiForgeryToken()

        <div class="form-group">
            @Html.LabelFor(model => model.Title, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-10">@Html.EditorFor(model => model.Title)</div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Subtitle, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-10">@Html.EditorFor(model => model.Subtitle)</div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label">@BiebResources.BookStrings.Authors</label>
            <div class="col-sm-10">@Html.ListBoxFor(model => model.AuthorIds, Model.AvailablePeople, new { @class = "form-control fancy-select" })</div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label">@BiebResources.BookStrings.Translators</label>
            <div class="col-sm-10">@Html.ListBoxFor(model => model.TranslatorIds, Model.AvailablePeople, new { @class = "form-control fancy-select" })</div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PublisherId, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-10">@Html.DropDownListFor(model => model.PublisherId, Model.AvailablePublishers, BiebResources.SharedStrings.NullOption, new { @class = "form-control fancy-select" })</div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Year, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-10">@Html.EditorFor(model => model.Year)</div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Iso639LanguageId, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-10">@Html.DropDownListFor(model => model.Iso639LanguageId, Model.AvailableIso639Languages, BiebResources.SharedStrings.NullOption, new { @class = "form-control fancy-select" })</div>
        </div>

    
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.ModifiedDateTicks)

        @Html.ValidationSummary()

        <div class="form-group">
            <div class="col-sm-10 col-sm-offset-2">
                <input type="submit" value="@BiebResources.SharedStrings.Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

Bieb.Web/Views/Stories/ItemList.cshtml
@model IEnumerable<Bieb.Web.Models.Stories.ViewStoryModel>

<table class="table table-bordered table-condensed table-striped table-hover">
    <tr>
        <th>@BiebResources.StoryStrings.TitleHeader</th>
        <th>@BiebResources.StoryStrings.ByHeader</th>
        <th>@BiebResources.StoryStrings.FromBookHeader</th>
    </tr>

@foreach (var story in Model) 
{
    <tr>
        <td>@Html.ActionLink(story.Title, "Details", new { controller = "Stories", id = story.Id })</td>
        <td>
            @Html.Raw(String.Join(",<br /> ", story.Authors.Select(p => Html.ActionLink(p.Text, "Details", new { controller = "People", id = p.Id }).ToHtmlString()).ToArray()))
        </td>
        <td>
            @if(story.Book != null)
            {
                <span>@Html.ActionLink(story.Book.Text, "Details", new { controller = "Books", id = story.Book.Id })</span>
            }
        </td>
    </tr>
}
</table>