Bieb.Web/Models/Publishers/EditPublisherModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using Bieb.Domain.Entities;

namespace Bieb.Web.Models.Publishers
{
    public class EditPublisherModel : EditEntityModel<Publisher>
    {
        [Required]
        [Display(Name = "Name", Prompt = "NamePlaceholder", ResourceType = typeof(BiebResources.PublisherStrings))]
        public string Name { get; set; }
    }
}

Bieb.Web/Models/Publishers/EditPublisherModelMapper.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Bieb.Domain.Entities;

namespace Bieb.Web.Models.Publishers
{
    public class EditPublisherModelMapper : EditEntityModelMapper<Publisher, EditPublisherModel>
    {
        public override void MergeEntityWithModel(Publisher entity, EditPublisherModel model)
        {
            base.MergeEntityWithModel(entity, model);
            entity.Name = model.Name;
        }

        public override EditPublisherModel ModelFromEntity(Publisher entity)
        {
            var model = base.ModelFromEntity(entity);

            model.Name = entity.Name;

            return model;
        }
    }
}

Bieb.Web/Models/Publishers/LinkablePublisherModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Bieb.Domain.Entities;

namespace Bieb.Web.Models.Publishers
{
    public class LinkablePublisherModel : LinkableEntityModel<Publisher>
    {
        public LinkablePublisherModel(Publisher publisher)
        {
            Id = publisher.Id;
            Text = publisher.Name;
        }
    }

    public static class LinkablePublisherModelExtensions
    {
        public static LinkablePublisherModel AsLinkablePublisherModel(this Publisher publisher)
        {
            return publisher == null
                       ? null
                       : new LinkablePublisherModel(publisher);
        }
    }
}

Bieb.Web/Models/Publishers/ViewPublisherModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Bieb.Domain.Entities;
using Bieb.Web.Models.Books;
using Bieb.Web.Models.Stories;

namespace Bieb.Web.Models.Publishers
{
    public class ViewPublisherModel : ViewEntityModel<Publisher>
    {
        public ViewPublisherModel(Publisher entity) : base(entity)
        { }

        public string Name { get; set; }

        public IEnumerable<ViewBookModel> MyBooks { get; set; }
        public IEnumerable<ViewBookModel> ReferenceBooks { get; set; }
        public IEnumerable<ViewStoryModel> Stories { get; set; } 
    }
}

Bieb.Web/Models/Publishers/ViewPublisherModelMapper.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Bieb.Domain.Entities;
using Bieb.Web.Models.Books;
using Bieb.Web.Models.Stories;

namespace Bieb.Web.Models.Publishers
{
    public class ViewPublisherModelMapper : IViewEntityModelMapper<Publisher, ViewPublisherModel>
    {
        private readonly IViewEntityModelMapper<Book, ViewBookModel> bookMapper;
        private readonly IViewEntityModelMapper<Story, ViewStoryModel> storyMapper;

        public ViewPublisherModelMapper(IViewEntityModelMapper<Book, ViewBookModel> bookMapper, IViewEntityModelMapper<Story, ViewStoryModel> storyMapper)
        {
            this.bookMapper = bookMapper;
            this.storyMapper = storyMapper;
        }

        public ViewPublisherModel ModelFromEntity(Publisher entity)
        {
            return new ViewPublisherModel(entity)
                       {
                           Name = entity.Name,
                           MyBooks = entity.MyBooks.Select(b => bookMapper.ModelFromEntity(b)),
                           ReferenceBooks = entity.ReferenceBooks.Select(b => bookMapper.ModelFromEntity(b)),
                           Stories = entity.Stories.Select(s => storyMapper.ModelFromEntity(s))
                       };
        }
    }
}

Bieb.Web/Controllers/PublisherController.cs
using System;
using System.Web.Mvc;
using Bieb.Domain.Entities;
using Bieb.Domain.Repositories;

namespace Bieb.Web.Controllers
{
    public class PublisherController : EntityController<Publisher>
    {
        public PublisherController(IEntityRepository<Publisher> repository)
            : base(repository)
        { }

        public override ActionResult Index(int pageSize = 25, int page = 1)
        {
            throw new NotImplementedException("Listing an index of publishers is not allowed. You can get there via Books and Stories");
        }

        protected override System.Linq.Expressions.Expression<Func<Publisher, IComparable>> SortFunc
        {
            get { return p => p.Name; }
        }
    }
}

Bieb.Web/Controllers/PublishersController.cs
using System;
using Bieb.Domain.Entities;
using Bieb.Domain.Repositories;
using Bieb.Web.Models;
using Bieb.Web.Models.Publishers;

namespace Bieb.Web.Controllers
{
    public class PublishersController : EntityController<Publisher, ViewPublisherModel, EditPublisherModel>
    {
        public PublishersController(IEntityRepository<Publisher> repository,
                                    IViewEntityModelMapper<Publisher, ViewPublisherModel> viewEntityModelMapper,
                                    IEditEntityModelMapper<Publisher, EditPublisherModel> editEntityModelMapper)
            : base(repository, viewEntityModelMapper, editEntityModelMapper)
        { }
        
        protected override System.Linq.Expressions.Expression<Func<Publisher, IComparable>> SortFunc
        {
            get { return p => p.Name; }
        }
    }
}

Bieb.Web/Views/Publishers/Details.cshtml
@model Bieb.Web.Models.Publishers.ViewPublisherModel

@{
    ViewBag.Title = Model.Name;
}

@if (User.Identity.IsAuthenticated)
{
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            @using (Html.BeginForm("Delete", "Publishers", FormMethod.Post, new { @class = "navbar-form navbar-left" }))
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(model => model.Id)
                
                <a href="@Url.Action("Create", "Publishers")" class="btn btn-default">
                    <i class="glyphicon glyphicon-star"></i>
                    <span class="hidden-xs">@BiebResources.SharedStrings.CreateNew</span>
                </a>
                
                <a href="@Url.Action("Edit", "Publishers", new { Model.Id })" class="btn btn-default">
                    <i class="glyphicon glyphicon-pencil"></i>
                    <span class="hidden-xs">@BiebResources.SharedStrings.Edit</span>
                </a>
                
                <button class="btn btn-default" type="submit" onclick="return confirm('@BiebResources.SharedStrings.SimpleConfirmQuestion')">
                    <i class="glyphicon glyphicon-trash"></i>
                    <span class="hidden-xs">@BiebResources.SharedStrings.Delete</span>
                </button>
            }
        </div>
    </nav>
}

<h1>@Model.Name</h1>

@if (Model.MyBooks.Any())
{
    <h4>@BiebResources.PublisherStrings.BooksFromThisPublisher</h4>
    Html.RenderPartial("~/Views/Books/ItemList.cshtml", Model.MyBooks);
}

@if (Model.Stories.Any())
{
    <h4>@BiebResources.PublisherStrings.StoriesFromThisPublisher</h4>
    Html.RenderPartial("~/Views/Stories/ItemList.cshtml", Model.Stories);
}

@if (Model.ReferenceBooks.Any())
{
    <h4>@BiebResources.PublisherStrings.ReferenceBooksFromThisPublisher</h4>
    Html.RenderPartial("~/Views/Books/ItemList.cshtml", Model.ReferenceBooks);
}

Bieb.Web/Views/Publishers/Edit.cshtml
@model Bieb.Web.Models.Publishers.EditPublisherModel

@{
    ViewBag.Title = "Edit";
}

<h1>@Model.Name</h1>

@using (Html.BeginForm("Save", "Publishers"))
{
    <div class="form-horizontal">
        @Html.AntiForgeryToken()

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-10">@Html.EditorFor(model => model.Name)</div>
        </div>

        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.ModifiedDateTicks)

        @Html.ValidationSummary()

        <div class="form-group">
            <div class="col-sm-10 col-sm-offset-2">
                <input type="submit" value="@BiebResources.SharedStrings.Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

Bieb.Web/Views/Publishers/Index.cshtml
@model PagedList.IPagedList<Bieb.Web.Models.Publishers.ViewPublisherModel>

@{
    ViewBag.Title = "Index";
}

@if (User.Identity.IsAuthenticated)
{
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-form">
                <a href="@Url.Action("Create", "Publishers")" class="btn btn-default">
                    <i class="glyphicon glyphicon-star"></i>
                    <span class="hidden-xs">@BiebResources.SharedStrings.CreateNew</span>
                </a>
            </div>
        </div>
    </nav>
}

<table class="table table-bordered table-striped table-hover table-condensed single-topic-table">
    <tr>
        <th>
            @BiebResources.SharedStrings.Publisher
        </th>
        <th>
            @BiebResources.SharedStrings.Books
        </th>
        <th>
            @BiebResources.SharedStrings.Stories
        </th>
    </tr>

@foreach (var publisher in Model) {
    <tr>
        <td class="main-topic">
            @Html.ActionLink(publisher.Name, "Details", new { id = publisher.Id, controller = "Publishers"})
        </td>
        <td>
            @publisher.MyBooks.Count()
        </td>
        <td>
            @publisher.Stories.Count()
        </td>
    </tr>
}

</table>

@{ Html.RenderPartial("PagerPartial", Model); }