Bieb.Web/Models/People/EditPersonModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using Bieb.Domain.Entities;

namespace Bieb.Web.Models.People
{
    public class EditPersonModel : EditEntityModel<Person>
    {
        public string FullName { get; set; }

        [Display(Name = "Gender", ResourceType = typeof(BiebResources.PeopleStrings))]
        public Gender Gender { get; set; }

        [Display(Name = "Title", Prompt = "TitlePlaceholder", ResourceType = typeof(BiebResources.PeopleStrings))]
        public string Title { get; set; }

        [Display(Name = "FirstName", Prompt = "FirstNamePlaceholder", ResourceType = typeof(BiebResources.PeopleStrings))]
        public string FirstName { get; set; }

        [Display(Name = "Prefix", Prompt = "PrefixPlaceholder", ResourceType = typeof(BiebResources.PeopleStrings))]
        public string Prefix { get; set; }

        [Required]
        [Display(Name = "Surname", Prompt = "SurnamePlaceholder", ResourceType = typeof(BiebResources.PeopleStrings))]
        public string Surname { get; set; }

        [Display(Name = "Nationality", Prompt = "NationalityPlaceholder", ResourceType = typeof(BiebResources.PeopleStrings))]
        public string Nationality { get; set; }

        [Display(Name = "DiedAt", Prompt = "DiedAtPlaceholder", ResourceType = typeof(BiebResources.PeopleStrings))]
        public string PlaceOfDeath { get; set; }

        [Display(Name = "BornAt", Prompt = "BornAtPlaceholder", ResourceType = typeof(BiebResources.PeopleStrings))]
        public string PlaceOfBirth { get; set; }

        [Display(Name = "Year", Prompt = "YearPlaceholder", ResourceType = typeof(BiebResources.PeopleStrings))]
        public int? DeathYear { get; set; }

        [Display(Name = "Month", Prompt = "MonthPlaceholder", ResourceType = typeof(BiebResources.PeopleStrings))]
        public int? DeathMonth { get; set; }

        [Display(Name = "Day", Prompt = "DayPlaceholder", ResourceType = typeof(BiebResources.PeopleStrings))]
        public int? DeathDay { get; set; }

        [Display(Name = "Year", Prompt = "YearPlaceholder", ResourceType = typeof(BiebResources.PeopleStrings))]
        public int? BirthYear { get; set; }

        [Display(Name = "Month", Prompt = "MonthPlaceholder", ResourceType = typeof(BiebResources.PeopleStrings))]
        public int? BirthMonth { get; set; }

        [Display(Name = "Day", Prompt = "DayPlaceholder", ResourceType = typeof(BiebResources.PeopleStrings))]
        public int? BirthDay { get; set; }

        [Display(Name = "ReviewText", Prompt = "ReviewTextPlaceholder", ResourceType = typeof(BiebResources.PeopleStrings))]
        [DataType(DataType.MultilineText)]
        public string ReviewText { get; set; }
    }
}

Bieb.Web/Models/People/EditPersonModelMapper.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Bieb.Domain.CustomDataTypes;
using Bieb.Domain.Entities;

namespace Bieb.Web.Models.People
{
    public class EditPersonModelMapper : EditEntityModelMapper<Person, EditPersonModel>
    {
        public override void MergeEntityWithModel(Person entity, EditPersonModel model)
        {
            base.MergeEntityWithModel(entity, model);

            entity.Title = model.Title;
            entity.FirstName = model.FirstName;
            entity.Prefix = model.Prefix;
            entity.Surname = model.Surname;

            entity.Gender = model.Gender;
            entity.Nationality = model.Nationality;

            entity.PlaceOfBirth = model.PlaceOfBirth;
            entity.PlaceOfDeath = model.PlaceOfDeath;

            entity.DateOfBirth = new UncertainDate(model.BirthYear, model.BirthMonth, model.BirthDay);
            entity.DateOfDeath = new UncertainDate(model.DeathYear, model.DeathMonth, model.DeathDay);

            entity.ReviewText = model.ReviewText;
        }

        public override EditPersonModel ModelFromEntity(Person entity)
        {
            var model = base.ModelFromEntity(entity);

            model.Title = entity.Title;
            model.FirstName = entity.FirstName;
            model.Prefix = entity.Prefix;
            model.Surname = entity.Surname;

            model.Gender = entity.Gender;
            model.Nationality = entity.Nationality;

            model.PlaceOfBirth = entity.PlaceOfBirth;
            model.PlaceOfDeath = entity.PlaceOfDeath;

            model.BirthDay = entity.DateOfBirth.Day;
            model.BirthMonth = entity.DateOfBirth.Month;
            model.BirthYear = entity.DateOfBirth.Year;

            model.DeathDay = entity.DateOfDeath.Day;
            model.DeathMonth = entity.DateOfDeath.Month;
            model.DeathYear = entity.DateOfDeath.Year;

            model.FullName = entity.FullName;

            model.ReviewText = entity.ReviewText;

            return model;
        }
    }
}

Bieb.Web/Models/People/LinkablePersonModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Bieb.Domain.Entities;

namespace Bieb.Web.Models.People
{
    public class LinkablePersonModel : LinkableEntityModel<Person>
    {
        public LinkablePersonModel(Person person)
        {
            Id = person.Id;
            Text = person.FullName;
        }
    }

    public static class LinkablePersonModelExtensions
    {
        public static LinkablePersonModel AsLinkablePersonModel(this Person person)
        {
            return person == null
                       ? null
                       : new LinkablePersonModel(person);
        }
    }
}

Bieb.Web/Models/People/ViewPersonModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Bieb.Domain.Entities;
using Bieb.Web.Models.Books;
using Bieb.Web.Models.Stories;

namespace Bieb.Web.Models.People
{
    public class ViewPersonModel : ViewEntityModel<Person>
    {
        public ViewPersonModel(Person entity) : base(entity)
        {
        }

        public string FullName { get; set; }

        public bool IsGenderKnown { get; set; }
        public string Gender { get; set; }
        public string GenderTooltip { get; set; }

        public bool IsNationalityKnown { get; set; }
        public string Nationality { get; set; }

        public string Roles { get; set; }

        public bool IsPlaceOfBirthKnown { get; set; }
        public string PlaceOfBirth { get; set; }

        public bool IsDateOfBirthKnown { get; set; }
        public string DateOfBirth { get; set; }

        public bool IsPlaceOfDeathKnown { get; set; }
        public string PlaceOfDeath { get; set; }

        public bool IsDateOfDeathKnown { get; set; }
        public string DateOfDeath { get; set; }

        public bool HasTags { get; set; }
        public string Tags { get; set; }

        public string ReviewText { get; set; }

        public IEnumerable<ViewBookModel> AuthoredBooks { get; set; }
        public IEnumerable<ViewBookModel> EditedBooks { get; set; }
        public IEnumerable<ViewBookModel> TranslatedBooks { get; set; }

        public IEnumerable<ViewStoryModel> TranslatedStories { get; set; }
        public IEnumerable<ViewStoryModel> AuthoredStories { get; set; } 
    }
}

Bieb.Web/Models/People/ViewPersonModelMapper.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Bieb.Domain.Entities;
using Bieb.Web.Localization;
using Bieb.Web.Models.Books;
using Bieb.Web.Models.Stories;

namespace Bieb.Web.Models.People
{
    public class ViewPersonModelMapper : IViewEntityModelMapper<Person, ViewPersonModel>
    {
        private readonly IViewEntityModelMapper<Book, ViewBookModel> bookMapper;
        private readonly IViewEntityModelMapper<Story, ViewStoryModel> storyMapper;

        public ViewPersonModelMapper(IViewEntityModelMapper<Book, ViewBookModel> bookMapper, IViewEntityModelMapper<Story, ViewStoryModel> storyMapper)
        {
            this.bookMapper = bookMapper;
            this.storyMapper = storyMapper;
        }

        public ViewPersonModel ModelFromEntity(Person entity)
        {
            return new ViewPersonModel(entity)
                       {
                           FullName = entity.FullName,
                           IsGenderKnown = entity.Gender != Gender.Unknown,
                           Gender = EnumDisplayer.GetResource(entity.Gender),
                           GenderTooltip = GenderTooltip(entity.Gender),
                           IsNationalityKnown = !string.IsNullOrEmpty(entity.Nationality),
                           Nationality = entity.Nationality,
                           Roles = string.Join(", ", entity.Roles.Select(EnumDisplayer.GetResource)),
                           IsPlaceOfBirthKnown = !string.IsNullOrEmpty(entity.PlaceOfBirth),
                           PlaceOfBirth = entity.PlaceOfBirth,
                           IsDateOfBirthKnown = !entity.DateOfBirth.IsCompletelyUnknown,
                           DateOfBirth = entity.DateOfBirth.ToString(),
                           IsPlaceOfDeathKnown = !string.IsNullOrEmpty(entity.PlaceOfDeath),
                           PlaceOfDeath = entity.PlaceOfDeath,
                           IsDateOfDeathKnown = !entity.DateOfDeath.IsCompletelyUnknown,
                           DateOfDeath = entity.DateOfDeath.ToString(),
                           HasTags = entity.Tags.Any(),
                           Tags = string.Join(", ", entity.Tags),
                           ReviewText = entity.ReviewText,
                           AuthoredBooks = entity.AuthoredBooks.Select(b => bookMapper.ModelFromEntity(b)),
                           EditedBooks = entity.EditedBooks.Select(b => bookMapper.ModelFromEntity(b)),
                           TranslatedBooks = entity.TranslatedBooks.Select(b => bookMapper.ModelFromEntity(b)),
                           TranslatedStories = entity.TranslatedStories.Select(s => storyMapper.ModelFromEntity(s)),
                           AuthoredStories = entity.AuthoredStories.Select(s => storyMapper.ModelFromEntity(s))
                       };
        }

        private static string GenderTooltip(Gender gender)
        {
            switch (gender)
            {
                case Gender.None:
                    return BiebResources.PeopleStrings.GenderTooltipNone;
                case Gender.Male:
                    return BiebResources.PeopleStrings.GenderTooltipMale;
                case Gender.Female:
                    return BiebResources.PeopleStrings.GenderTooltipFemale;
                case Gender.Unknown:
                default:
                    return BiebResources.PeopleStrings.GenderTooltipUnknown;
            }
        }
    }
}

Bieb.Web/Controllers/PeopleController.cs
using System;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web.Mvc;
using Bieb.Domain.Entities;
using Bieb.Domain.Repositories;
using Bieb.Web.Models;
using Bieb.Web.Models.People;

namespace Bieb.Web.Controllers
{
    public class PeopleController : EntityController<Person, ViewPersonModel, EditPersonModel>
    {
        private const int MaxNumberOfBirthDates = 5;

        public PeopleController(IEntityRepository<Person> repository,
                                IViewEntityModelMapper<Person, ViewPersonModel> viewEntityModelMapper,
                                IEditEntityModelMapper<Person, EditPersonModel> editEntityModelMapper)
            : base(repository, viewEntityModelMapper, editEntityModelMapper)
        { }
        
        protected override System.Linq.Expressions.Expression<Func<Person, IComparable>> SortFunc
        {
            get { return p => p.Surname; }
        }

        public ActionResult TodaysBirthDates()
        {
            return BirthDates(DateTime.Now);
        }

        public ActionResult BirthDates(DateTime referenceDate)
        {
            var people = Repository.Items
                            .Where(p => p.DateOfBirthFrom.HasValue
                                        && p.DateOfBirthUntil.HasValue
                                        && p.DateOfBirthFrom.Value.Equals(p.DateOfBirthUntil.Value) // would prefer p.DateOfBirth.IsCertain, but that won't roll with NHibernate
                                        && p.DateOfBirthFrom.Value.Day == referenceDate.Day
                                        && p.DateOfBirthFrom.Value.Month == referenceDate.Month)
                            .Take(MaxNumberOfBirthDates)
                            .Select(p => p.AsLinkablePersonModel());

            return PartialView(people);
        }
    }
}

Bieb.Web/Controllers/PersonController.cs
using System;
using Bieb.Domain.Entities;
using Bieb.Domain.Repositories;

namespace Bieb.Web.Controllers
{
    public class PersonController : EntityController<Person>
    {
        public PersonController(IEntityRepository<Person> repository)
            : base(repository)
        { }


        protected override System.Linq.Expressions.Expression<Func<Person, IComparable>> SortFunc
        {
            get { return p => p.Surname; }
        }
    }
}

Bieb.Web/Views/People/Card.cshtml
@model Bieb.Web.Models.People.ViewPersonModel

<div class="panel panel-primary">
    <div class="panel-body">
        <h1>
            @Html.DisplayFor(model => model.FullName)
        </h1>

        <p class="lead">
            @if (Model.IsGenderKnown)
            {
                <span title="@Model.GenderTooltip">@Model.Gender</span>
            }

            @if (Model.Nationality != null)
            {
                @Html.ImageFlagFor(Model.Nationality)
            }

            @string.Join(", ", Model.Roles)
        </p>

        <ul>
            @if (Model.IsDateOfBirthKnown)
            {
                <li>
                    @BiebResources.PeopleStrings.BornOn: @Model.DateOfBirth
                </li>
            }

            @if (Model.PlaceOfBirth != null)
            {
                <li>
                    @BiebResources.PeopleStrings.BornAt: @Html.DisplayFor(model => model.PlaceOfBirth)
                </li>
            }
            
            @if (Model.IsDateOfDeathKnown)
            {
                <li>
                    @BiebResources.PeopleStrings.DiedOn: @Model.DateOfDeath
                </li>
            }

            @if (Model.PlaceOfDeath != null)
            {
                <li>
                    @BiebResources.PeopleStrings.DiedAt: @Html.DisplayFor(model => model.PlaceOfDeath)
                </li>
            }

            @if (Model.Tags.Any())
            { 
                <li>
                    @BiebResources.SharedStrings.Tags:
                    @string.Join(", ", Model.Tags)
                </li>
            }
        </ul>

        <p>@BiebResources.PeopleStrings.RequestForAdditionalInfo</p>
    </div>
</div>

Bieb.Web/Views/People/Details.cshtml
@model Bieb.Web.Models.People.ViewPersonModel

@{
    ViewBag.Title = Model.FullName;
}


@if (User.Identity.IsAuthenticated)
{
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            @using (Html.BeginForm("Delete", "People", FormMethod.Post, new { @class = "navbar-form navbar-left" }))
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(model => model.Id)
                
                <a href="@Url.Action("Create", "People")" class="btn btn-default">
                    <i class="glyphicon glyphicon-star"></i>
                    <span class="hidden-xs">@BiebResources.SharedStrings.CreateNew</span>
                </a>
                
                <a href="@Url.Action("Edit", "People", new { Model.Id })" class="btn btn-default">
                    <i class="glyphicon glyphicon-pencil"></i>
                    <span class="hidden-xs">@BiebResources.SharedStrings.Edit</span>
                </a>
                
                <button class="btn btn-default" type="submit" onclick="return confirm('@BiebResources.SharedStrings.SimpleConfirmQuestion')">
                    <i class="glyphicon glyphicon-trash"></i>
                    <span class="hidden-xs">@BiebResources.SharedStrings.Delete</span>
                </button>
            }
        </div>
    </nav>
}

<div class="row">

    <div class="col-md-4">
        @{ Html.RenderPartial("Card", Model); }
    </div>

    <div class="col-md-8">
        <p>@Model.ReviewText</p>
        
        @if (Model.AuthoredBooks.Any())
        {
            <h2>@BiebResources.PeopleStrings.AuthoredBooks</h2>
            Html.RenderPartial("~/Views/Books/ItemList.cshtml", Model.AuthoredBooks);
        }

        @if (Model.EditedBooks.Any())
        {
            <h2>@BiebResources.PeopleStrings.EditedBooks</h2>
            Html.RenderPartial("~/Views/Books/ItemList.cshtml", Model.EditedBooks);
        }

        @if (Model.TranslatedBooks.Any())
        {
            <h2>@BiebResources.PeopleStrings.TranslatedBooks</h2>
            Html.RenderPartial("~/Views/Books/ItemList.cshtml", Model.TranslatedBooks);
        }

        @if (Model.TranslatedStories.Any())
        {
            <h2>@BiebResources.PeopleStrings.TranslatedStories</h2>
            Html.RenderPartial("~/Views/Stories/ItemList.cshtml", Model.TranslatedStories);
        }

        @if (Model.AuthoredStories.Any())
        {
            // TODO: Split between short stories and novels
            <h2>@BiebResources.PeopleStrings.AuthoredStories</h2>
            Html.RenderPartial("~/Views/Stories/ItemList.cshtml", Model.AuthoredStories);
        }

        @{ Html.RenderPartial("MoreInfo", Model); }
    </div>

</div>

Bieb.Web/Views/People/Edit.cshtml
@model Bieb.Web.Models.People.EditPersonModel

@{
    ViewBag.Title = "Edit";
}

<h1>@Model.FullName</h1>

@using (Html.BeginForm("Save", "People"))
{
    <div class="form-horizontal">
        @Html.AntiForgeryToken()

        <div class="form-group">
            <label class="col-sm-2 control-label">@BiebResources.PeopleStrings.NameGroupLabel</label>
            <div class="row col-sm-10">
                <div class="col-sm-2">@Html.EditorFor(model => model.Title)</div>
                <div class="col-sm-3">@Html.EditorFor(model => model.FirstName)</div>
                <div class="col-sm-2">@Html.EditorFor(model => model.Prefix)</div>
                <div class="col-sm-4">@Html.EditorFor(model => model.Surname)</div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-10">@Html.DropDownListFor(model => model.Gender, new SelectList(Enum.GetValues(typeof(Bieb.Domain.Entities.Gender))), new { @class = "form-control fancy-select" })</div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nationality, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-10">@Html.EditorFor(model => model.Nationality)</div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PlaceOfBirth, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-10">@Html.EditorFor(model => model.PlaceOfBirth)</div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label">@BiebResources.PeopleStrings.BornOn</label>
            <div class="row col-sm-10">
                <div class="col-sm-3">@Html.EditorFor(model => model.BirthDay)</div>
                <div class="col-sm-3">@Html.EditorFor(model => model.BirthMonth)</div>
                <div class="col-sm-5">@Html.EditorFor(model => model.BirthYear)</div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PlaceOfDeath, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-10">@Html.EditorFor(model => model.PlaceOfDeath)</div>
        </div>

        <div class="form-group">
            <label class="col-sm-2 control-label">@BiebResources.PeopleStrings.DiedOn</label>
            <div class="row col-sm-10">
                <div class="col-xs-3">@Html.EditorFor(model => model.DeathDay)</div>
                <div class="col-xs-3">@Html.EditorFor(model => model.DeathMonth)</div>
                <div class="col-xs-5">@Html.EditorFor(model => model.DeathYear)</div>
            </div>
        </div>
        
        <div class="form-group">
            <label class="col-sm-2 control-label">@BiebResources.PeopleStrings.ReviewText</label>
            <div class="col-sm-10">@Html.EditorFor(model => model.ReviewText)</div>
        </div>

        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.ModifiedDateTicks)

        @Html.ValidationSummary()

        <div class="form-group">
            <div class="col-sm-10 col-sm-offset-2">
                <input type="submit" value="@BiebResources.SharedStrings.Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

Bieb.Web/Views/People/Index.cshtml
@model PagedList.IPagedList<Bieb.Web.Models.People.ViewPersonModel>

@{
    ViewBag.Title = "All People";
}

@if (User.Identity.IsAuthenticated)
{
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-form">
                <a href="@Url.Action("Create", "People")" class="btn btn-default">
                    <i class="glyphicon glyphicon-star"></i>
                    <span class="hidden-xs">@BiebResources.SharedStrings.CreateNew</span>
                </a>
            </div>
        </div>
    </nav>
}

<p>@BiebResources.PeopleStrings.IndexIntroduction</p>

<table class="table table-bordered table-striped table-hover table-condensed single-topic-table">
    <tr>
        <th>
            <span class="hidden-xs hidden-sm">
                @BiebResources.PeopleStrings.Gender
            </span>
        </th>
        <th>
            <span class="hidden-xs hidden-sm">
                @BiebResources.PeopleStrings.NationalityHeader
            </span>
        </th>
        <th>
            @BiebResources.PeopleStrings.NameHeader
        </th>
        <th>
            @BiebResources.PeopleStrings.RolesHeader
        </th>
    </tr>

@foreach (var person in Model)
{
    <tr>
        <td>
            @Html.DisplayFor(modelperson => person.Gender)
        </td>
        <td>
            @if (person.IsNationalityKnown)
            { 
                @Html.ImageFlagFor(person.Nationality)
            }
        </td>
        <td class="main-topic">
            @Html.ActionLink(person.FullName, "Details", new { id = person.Id })
        </td>
        <td> 
            @person.Roles
        </td>
    </tr>
}

</table>

@{ Html.RenderPartial("PagerPartial", Model); }

Bieb.Web/Views/People/ItemList.cshtml
@model IEnumerable<Bieb.Web.Models.People.ViewPersonModel>
    
<div class="row">
@foreach (var person in Model) 
{
    <div class="col-lg-4 col-sm-6">
        <div class="panel panel-default panel-body">
            <h4>@Html.ActionLink(person.FullName, "Details", new { controller = "People", id = person.Id })</h4>
            <p>
                @if (person.IsGenderKnown)
                {
                    @person.Gender
                }

                @if (person.IsNationalityKnown)
                {
                    @Html.ImageFlagFor(person.Nationality)
                }
        
                @person.Roles
            </p>
        </div>
    </div>
}
</div>

Bieb.Web/Views/People/MoreInfo.cshtml
@model Bieb.Web.Models.People.ViewPersonModel

<section>
    
    <section>
        <h4>@BiebResources.PeopleStrings.FindPersonOn</h4>
        <ul>
            <li><a href="http://www.google.com/search?q=Person+@Url.Encode(Model.FullName)">Google</a></li>
            <li><a href="http://en.wikipedia.org/wiki/Special:Search?search=@Url.Encode(Model.FullName)">Wikipedia</a></li>
            <li><a href="http://www.amazon.com/s?url=search-alias%3Daps&field-keywords=@Url.Encode(Model.FullName)">Amazon</a></li>
            <li><a href="http://www.goodreads.com/search?query=@Url.Encode(Model.FullName)">Goodreads</a></li>
        </ul>
    </section>

</section>

Bieb.Web/Views/People/TodaysBirthDates.cshtml
@model IEnumerable<Bieb.Web.Models.People.LinkablePersonModel>
@if (Model.Any())
{
    <ul>
        @foreach (var person in Model)
        {
            <li>
                @Html.ActionLink(person.Text, "Details", new { id = person.Id, controller = "People" })
            </li>
        }
    </ul>   
}
else
{
    <p>@BiebResources.PeopleStrings.NobodyBornToday</p>
    <blockquote>@BiebResources.PeopleStrings.NobodyQuote</blockquote>
}