Bieb.Web/Models/Series/EditSeriesModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web.Mvc;

namespace Bieb.Web.Models.Series
{
    public class EditSeriesModel : EditEntityModel<Domain.Entities.Series>
    {
        public EditSeriesModel()
        {
            BookIds = new int[0];
        }

        [Required]
        [Display(Name = "Title", Prompt = "TitlePlaceholder", ResourceType = typeof(BiebResources.SeriesStrings))]
        public string Title { get; set; }

        [Display(Name = "Subtitle", Prompt = "SubtitlePlaceholder", ResourceType = typeof(BiebResources.SeriesStrings))]
        public string Subtitle { get; set; }

        public SelectList AvailableBooks { get; set; }

        [Display(Name = "Books", ResourceType = typeof(BiebResources.SeriesStrings))]
        public int[] BookIds { get; set; }
    }
}

Bieb.Web/Models/Series/EditSeriesModelMapper.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Bieb.Domain.Entities;
using Bieb.Domain.Repositories;

namespace Bieb.Web.Models.Series
{
    public class EditSeriesModelMapper : EditEntityModelMapper<Domain.Entities.Series, EditSeriesModel>
    {
        private readonly IEnumerable<Book> books; 

        public EditSeriesModelMapper(IEntityRepository<Book> books)
        {
            this.books = books.Items;
        }

        public override void MergeEntityWithModel(Domain.Entities.Series entity, EditSeriesModel model)
        {
            base.MergeEntityWithModel(entity, model);

            entity.Title = model.Title;
            entity.Subtitle = model.Subtitle;

            var i = 0;

            entity.Books.Clear();
            
            foreach (var bookId in model.BookIds)
            {
                var book = books.FirstOrDefault(b => b.Id == bookId);
                
                if (book == null)
                {
                    throw new MappingException("Provided book Id could not be found in the list of available books.");
                }

                entity.Books.Add(i, book);

                i++;
            }
        }

        public override EditSeriesModel ModelFromEntity(Domain.Entities.Series entity)
        {
            var model = base.ModelFromEntity(entity);

            model.Title = entity.Title;
            model.Subtitle = entity.Subtitle;

            model.AvailableBooks = new SelectList(books.OrderBy(b => b.Title), "Id", "TitleSort");

            model.BookIds = entity.Books.Select(book => book.Value.Id).ToArray();

            return model;
        }
    }
}

Bieb.Web/Models/Series/LinkableSeriesModel.cs
using System;
using System.Collections.Generic;
using System.Linq;

namespace Bieb.Web.Models.Series
{
    public class LinkableSeriesModel : LinkableEntityModel<Domain.Entities.Series>
    {
        public LinkableSeriesModel(Domain.Entities.Series series)
        {
            Id = series.Id;
            Text = series.Title;
        }
    }

    public static class LinkableSeriesModelExtensions
    {
        public static LinkableSeriesModel AsLinkableSeriesModel(this Domain.Entities.Series series)
        {
            return series == null
                       ? null
                       : new LinkableSeriesModel(series);
        }
    }
}

Bieb.Web/Models/Series/ViewSeriesModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Bieb.Web.Models.Books;

namespace Bieb.Web.Models.Series
{
    public class ViewSeriesModel : ViewEntityModel<Domain.Entities.Series>
    {
        public ViewSeriesModel(Domain.Entities.Series series)
            : base(series)
        { }

        public string Title { get; set; }
        public string Subtitle { get; set; }
        public IEnumerable<ViewBookModel> Books { get; set; }
    }
}

Bieb.Web/Models/Series/ViewSeriesModelMapper.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Bieb.Domain.Entities;
using Bieb.Web.Models.Books;

namespace Bieb.Web.Models.Series
{
    public class ViewSeriesModelMapper : IViewEntityModelMapper<Domain.Entities.Series, ViewSeriesModel>
    {
        private readonly IViewEntityModelMapper<Book, ViewBookModel> bookMapper;

        public ViewSeriesModelMapper(IViewEntityModelMapper<Book, ViewBookModel> bookMapper)
        {
            this.bookMapper = bookMapper;
        }

        public ViewSeriesModel ModelFromEntity(Domain.Entities.Series entity)
        {
            return new ViewSeriesModel(entity)
                       {
                           Title = entity.Title,
                           Subtitle = entity.Subtitle,
                           Books = entity.Books.Values.Select(b => bookMapper.ModelFromEntity(b))
                       };
        }
    }
}

Bieb.Web/Controllers/SeriesController.cs
using System;
using Bieb.Domain.Entities;
using Bieb.Domain.Repositories;
using Bieb.Web.Models;
using Bieb.Web.Models.Series;

namespace Bieb.Web.Controllers
{
    public class SeriesController : EntityController<Series, ViewSeriesModel, EditSeriesModel>
    {
        public SeriesController(IEntityRepository<Series> repository, 
                                IViewEntityModelMapper<Series, ViewSeriesModel> viewEntityModelMapper,
                                IEditEntityModelMapper<Series, EditSeriesModel> editEntityModelMapper)
            : base(repository, viewEntityModelMapper, editEntityModelMapper)
        { }


        protected override System.Linq.Expressions.Expression<Func<Series, IComparable>> SortFunc
        {
            get { return s => s.TitleSort; }
        }
    }
}

Bieb.Web/Views/Series/Details.cshtml
@model Bieb.Web.Models.Series.ViewSeriesModel

@{
    ViewBag.Title = "Details";
}

@if (User.Identity.IsAuthenticated)
{
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            @using (Html.BeginForm("Delete", "Series", FormMethod.Post, new { @class = "navbar-form navbar-left" }))
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(model => model.Id)
                
                <a href="@Url.Action("Create", "Series")" class="btn btn-default">
                    <i class="glyphicon glyphicon-star"></i>
                    <span class="hidden-xs">@BiebResources.SharedStrings.CreateNew</span>
                </a>
                
                <a href="@Url.Action("Edit", "Series", new { Model.Id })" class="btn btn-default">
                    <i class="glyphicon glyphicon-pencil"></i>
                    <span class="hidden-xs">@BiebResources.SharedStrings.Edit</span>
                </a>
                
                <button class="btn btn-default" type="submit" onclick="return confirm('@BiebResources.SharedStrings.SimpleConfirmQuestion')">
                    <i class="glyphicon glyphicon-trash"></i>
                    <span class="hidden-xs">@BiebResources.SharedStrings.Delete</span>
                </button>
            }
        </div>
    </nav>
}

<h1>@Html.DisplayFor(model => model.Title)</h1>

@Html.ShowIfNotNull(Model.Subtitle, "h2")

<div class="row">
    <div class="col-xs-12">
        <h4>@BiebResources.SharedStrings.Books</h4>
        @{ Html.RenderPartial("~/Views/Books/ItemList.cshtml", Model.Books); }
    </div>
</div>

Bieb.Web/Views/Series/Edit.cshtml
@model Bieb.Web.Models.Series.EditSeriesModel

@{
    ViewBag.Title = "Edit";
}

<h1>@Model.Title</h1>

@using (Html.BeginForm("Save", "Series"))
{
    <div class="form-horizontal">
        @Html.AntiForgeryToken()

        <div class="form-group">
            @Html.LabelFor(model => model.Title, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-10">@Html.EditorFor(model => model.Title)</div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Subtitle, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-10">@Html.EditorFor(model => model.Subtitle)</div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BookIds, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-10">@Html.ListBoxFor(model => model.BookIds, Model.AvailableBooks, new { @class = "form-control fancy-select" })</div>
        </div>

        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.ModifiedDateTicks)

        @Html.ValidationSummary()

        <div class="form-group">
            <div class="col-sm-10 col-sm-offset-2">
                <input type="submit" value="@BiebResources.SharedStrings.Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

Bieb.Web/Views/Series/Index.cshtml
@model PagedList.IPagedList<Bieb.Web.Models.Series.ViewSeriesModel>

@{
    ViewBag.Title = "All Series";
}

@if (User.Identity.IsAuthenticated)
{
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-form">
                <a href="@Url.Action("Create", "Series")" class="btn btn-default">
                    <i class="glyphicon glyphicon-star"></i>
                    <span class="hidden-xs">@BiebResources.SharedStrings.CreateNew</span>
                </a>
            </div>
        </div>
    </nav>
}

<p>@BiebResources.SeriesStrings.IndexIntroduction</p>

<table class="table table-bordered table-striped table-hover table-condensed single-topic-table">
    <tr>
        <th>
            @BiebResources.SeriesStrings.TitleHeader
        </th>
        <th>
            @BiebResources.SeriesStrings.BooksInThisSeries
        </th>
    </tr>

@foreach (var series in Model) {
    <tr>
        <td>
            @Html.ActionLink(series.Title, "Details", new { id=series.Id })
        </td>
        <td class="main-topic">
            @string.Join(", ", series.Books.Select(s => s.Title))
        </td>
    </tr>
}

</table>

@{ Html.RenderPartial("PagerPartial", Model); }